"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Plus, Save, ExternalLink, Trash2 } from "lucide-react";

type Block = { id: string; type: "text" | "textarea" | "email" | "select" | "choice" | "file"; label: string; required?: boolean; options?: string[] };
type FormRecord = { id: string; title: string; slug: string; description_markdown?: string; blocks: Block[]; is_published: boolean };

const newBlock = (type: Block["type"]): Block => ({ id: crypto.randomUUID(), type, label: type === "file" ? "Upload supporting documents" : "Untitled question", required: false, options: type === "select" || type === "choice" ? ["Option 1", "Option 2"] : undefined });

export default function FormsPage() {
  const [forms, setForms] = useState<FormRecord[]>([]);
  const [active, setActive] = useState<FormRecord | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [submissions, setSubmissions] = useState<{ id: string; created_at: string; answers: Record<string, unknown> }[]>([]);

  const refresh = () => fetch("/api/forms").then((r) => r.ok ? r.json() : []).then(setForms);
  useEffect(() => { refresh(); }, []);
  const update = (patch: Partial<FormRecord>) => setActive((form) => form ? { ...form, ...patch } : form);
  const loadSubmissions = () => active?.id && fetch(`/api/forms/${active.id}/submissions`).then((r) => r.ok ? r.json() : []).then(setSubmissions);
  const add = () => setActive({ id: "", title: "Untitled form", slug: "untitled-form", description_markdown: "", blocks: [], is_published: false });
  async function save(event: FormEvent) {
    event.preventDefault(); if (!active) return;
    setSaving(true); setError("");
    const response = await fetch(active.id ? `/api/forms/${active.id}` : "/api/forms", { method: active.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: active.title, slug: active.slug, description_markdown: active.description_markdown, blocks: active.blocks, is_published: active.is_published }) });
    const payload = await response.json(); setSaving(false);
    if (!response.ok) return setError(payload.detail || "Could not save form");
    setActive(payload); refresh();
  }
  if (!active) return <main className="mx-auto max-w-6xl p-4 sm:p-8"><div className="flex items-end justify-between gap-4 border-b-2 border-border pb-6"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-orange">Forms</p><h1 className="mt-2 font-heading text-4xl font-black uppercase">Build a form</h1><p className="mt-2 max-w-xl text-zinc-300">A block-first builder for application, registration, and feedback forms.</p></div><button onClick={add} className="inline-flex min-h-11 items-center gap-2 border-2 border-black bg-orange px-4 font-bold text-black shadow-light transition-transform active:translate-x-1 active:translate-y-1 active:shadow-none"><Plus size={18}/> New form</button></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{forms.map((form) => <button key={form.id} onClick={() => setActive(form)} className="border-2 border-border bg-[#141418] p-5 text-left shadow-light transition-transform hover:-translate-y-0.5 active:translate-x-1 active:translate-y-1 active:shadow-none"><p className="font-heading text-xl font-black">{form.title}</p><p className="mt-2 font-mono text-xs text-zinc-400">/form/{form.slug} · {form.blocks.length} blocks · {form.is_published ? "Published" : "Draft"}</p></button>)}</div>{forms.length === 0 && <p className="mt-12 border-2 border-dashed border-zinc-600 p-8 text-center text-zinc-300">Start with a title, then add question blocks. Your public link stays stable at `/form/your-slug`.</p>}</main>;
  return <main className="mx-auto max-w-6xl p-4 sm:p-8"><form onSubmit={save} className="grid gap-6 lg:grid-cols-[1fr_290px]"><section className="space-y-5"><header className="border-2 border-border bg-[#141418] p-5 shadow-dark"><input aria-label="Form title" value={active.title} onChange={(e) => update({ title: e.target.value })} className="w-full bg-transparent font-heading text-3xl font-black outline-none"/><input aria-label="Form slug" value={active.slug} onChange={(e) => update({ slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} className="mt-3 w-full border-2 border-border bg-black px-3 py-2 font-mono text-sm outline-none focus:border-orange"/><textarea aria-label="Form description" value={active.description_markdown} onChange={(e) => update({ description_markdown: e.target.value })} placeholder="Description (Markdown supported)" className="mt-3 min-h-24 w-full border-2 border-border bg-black p-3 text-sm leading-6 outline-none focus:border-orange"/></header>
  {active.blocks.map((block, index) => <article key={block.id} className="border-2 border-border bg-[#141418] p-5 shadow-light"><div className="flex items-center gap-3"><span className="font-mono text-xs text-orange">{index + 1}</span><input aria-label={`Question ${index + 1}`} value={block.label} onChange={(e) => update({ blocks: active.blocks.map((item) => item.id === block.id ? { ...item, label: e.target.value } : item) })} className="flex-1 bg-transparent font-heading text-lg font-bold outline-none"/><button type="button" aria-label="Remove block" onClick={() => update({ blocks: active.blocks.filter((item) => item.id !== block.id) })} className="min-h-11 min-w-11 text-zinc-400 hover:text-red-400"><Trash2 size={18}/></button></div><div className="mt-4 flex flex-wrap gap-3 font-mono text-xs"><span className="border border-zinc-600 px-2 py-1 uppercase">{block.type}</span><label className="flex items-center gap-2"><input type="checkbox" checked={!!block.required} onChange={(e) => update({ blocks: active.blocks.map((item) => item.id === block.id ? { ...item, required: e.target.checked } : item) })}/> Required</label></div></article>)}
  <div className="flex flex-wrap gap-2">{(["text", "textarea", "email", "select", "choice", "file"] as const).map((type) => <button key={type} type="button" onClick={() => update({ blocks: [...active.blocks, newBlock(type)] })} className="min-h-11 border-2 border-border bg-[#141418] px-3 font-mono text-xs font-bold uppercase hover:bg-orange hover:text-black">+ {type}</button>)}</div></section>
  <aside className="h-fit border-2 border-border bg-[#141418] p-5 shadow-light lg:sticky lg:top-6"><label className="flex gap-3 text-sm font-bold"><input type="checkbox" checked={active.is_published} onChange={(e) => update({ is_published: e.target.checked })}/> Publish this form</label>{active.id && <><Link target="_blank" href={`/form/${active.slug}`} className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm text-orange underline"><ExternalLink size={16}/> Open public form</Link><button type="button" onClick={loadSubmissions} className="mt-3 w-full min-h-11 border-2 border-border px-3 text-xs font-bold uppercase">View responses ({submissions.length || "…"})</button>{submissions.slice(0, 5).map((submission) => <details key={submission.id} className="mt-2 border border-zinc-600 p-2 text-xs"><summary>{new Date(submission.created_at).toLocaleString()}</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap text-zinc-300">{JSON.stringify(submission.answers, null, 2)}</pre></details>)}</>}<button disabled={saving} className="mt-6 flex min-h-11 w-full items-center justify-center gap-2 border-2 border-black bg-main font-bold text-white shadow-light disabled:opacity-60"><Save size={17}/>{saving ? "Saving…" : "Save form"}</button>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<button type="button" onClick={() => setActive(null)} className="mt-3 w-full text-sm text-zinc-300 underline">Back to forms</button></aside></form></main>;
}
