"""
Finance router — GOBITSNBYTES FOUNDATION Virtual Ledger + Banking API.

Powered by RazorpayX (future real integration). All money flows are on paper only —
a single real current account sits underneath. Requires IAM-based authentication
via signed internal proxy headers and finance.* permissions.
"""

from __future__ import annotations

import random
import string
import uuid
from datetime import datetime, timedelta, timezone
from typing import Annotated

from fastapi import APIRouter, HTTPException, Query, status
from sqlalchemy import func, select

from app.db.models import MoneyRequest, VirtualAccount, VirtualCard, VirtualTransaction
from app.dependencies import CurrentUserDep, DbSession
from app.iam.policy import can, require_permission
from app.schemas.finance import (
    MoneyRequestCreate,
    MoneyRequestOut,
    MoneyRequestReview,
    VirtualAccountCreate,
    VirtualAccountOut,
    VirtualAccountUpdate,
    VirtualCardCreate,
    VirtualCardOut,
    VirtualCardUpdate,
    VirtualTransactionOut,
    CardSimulationPayload,
)

router = APIRouter(prefix="/api/finance", tags=["finance"])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _gen_account_number() -> str:
    """Generate a fake unique 12-digit account number."""
    return "".join(random.choices(string.digits, k=12))


async def _require_finance(db, user, perm: str) -> None:
    """Check if the user is a finance admin OR has a specific finance permission constraint."""
    is_admin = await can(db, user, "finance.admin")
    if is_admin:
        return
    await require_permission(db, user, perm)


# ---------------------------------------------------------------------------
# Health & Info
# ---------------------------------------------------------------------------

@router.get("/health")
async def finance_health() -> dict:
    """Return health status details of the virtual finance services."""
    return {"status": "ok", "service": "finance"}


@router.get("/info")
async def finance_info() -> dict:
    """Provide descriptive metadata and current contact information for GOBITSNBYTES FOUNDATION finance tracking."""
    return {
        "name": "GOBITSNBYTES FOUNDATION Finance API",
        "version": "0.2.0",
        "description": (
            "Internal finance operations module for the bits&bytes network. "
            "Handles virtual budgeting, expense tracking, reimbursements, and "
            "financial reporting across all city forks. Powered by RazorpayX."
        ),
        "status": "active",
        "organization": "GOBITSNBYTES FOUNDATION",
        "banking_provider": "RazorpayX",
        "contact": "finance@gobitsnbytes.org",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Virtual Accounts
# ---------------------------------------------------------------------------

@router.get("/accounts", response_model=list[VirtualAccountOut])
async def list_accounts(
    db: DbSession,
    current_user: CurrentUserDep,
    active_only: Annotated[bool, Query()] = True,
) -> list[VirtualAccount]:
    """List virtual ledger accounts. Active-only toggle is enabled by default."""
    await _require_finance(db, current_user, "finance.accounts.read")
    stmt = select(VirtualAccount)
    if active_only:
        stmt = stmt.where(VirtualAccount.is_active.is_(True))
    stmt = stmt.order_by(VirtualAccount.created_at.desc())
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.post("/accounts", response_model=VirtualAccountOut, status_code=status.HTTP_201_CREATED)
async def create_account(
    payload: VirtualAccountCreate,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualAccount:
    """Create a new virtual ledger account with an autogenerated account number."""
    await _require_finance(db, current_user, "finance.accounts.create")

    # Generate a unique account number
    for _ in range(10):
        acc_no = _gen_account_number()
        exists = await db.execute(
            select(VirtualAccount).where(VirtualAccount.account_number == acc_no)
        )
        if not exists.scalar_one_or_none():
            break

    account = VirtualAccount(
        owner_id=payload.owner_id,
        name=payload.name,
        description=payload.description,
        account_number=acc_no,
    )
    db.add(account)
    await db.commit()
    await db.refresh(account)
    return account


@router.get("/accounts/{account_id}", response_model=VirtualAccountOut)
async def get_account(
    account_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualAccount:
    """Retrieve details for a specific virtual ledger account by UUID."""
    await _require_finance(db, current_user, "finance.accounts.read")
    account = await db.get(VirtualAccount, account_id)
    if not account:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found.")
    return account


@router.patch("/accounts/{account_id}", response_model=VirtualAccountOut)
async def update_account(
    account_id: uuid.UUID,
    payload: VirtualAccountUpdate,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualAccount:
    """Update profile configuration or status values for a virtual ledger account."""
    await _require_finance(db, current_user, "finance.accounts.manage")
    account = await db.get(VirtualAccount, account_id)
    if not account:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found.")
    for field, value in payload.model_dump(exclude_unset=True).items():
        setattr(account, field, value)
    await db.commit()
    await db.refresh(account)
    return account


@router.delete("/accounts/{account_id}", status_code=status.HTTP_204_NO_CONTENT)
async def deactivate_account(
    account_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> None:
    """Soft delete/deactivate a virtual ledger account."""
    await _require_finance(db, current_user, "finance.accounts.manage")
    account = await db.get(VirtualAccount, account_id)
    if not account:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found.")
    account.is_active = False
    await db.commit()


@router.get("/accounts/{account_id}/cards", response_model=list[VirtualCardOut])
async def list_account_cards(
    account_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> list[VirtualCard]:
    """List virtual debit/credit cards linked to a specific virtual ledger account."""
    await _require_finance(db, current_user, "finance.cards.read")
    result = await db.execute(
        select(VirtualCard).where(VirtualCard.account_id == account_id)
    )
    return list(result.scalars().all())


# ---------------------------------------------------------------------------
# Virtual Cards
# ---------------------------------------------------------------------------

@router.get("/cards", response_model=list[VirtualCardOut])
async def list_cards(
    db: DbSession,
    current_user: CurrentUserDep,
    active_only: Annotated[bool, Query()] = True,
) -> list[VirtualCard]:
    """List all issued virtual cards. Active-only toggle is enabled by default."""
    await _require_finance(db, current_user, "finance.cards.read")
    stmt = select(VirtualCard)
    if active_only:
        stmt = stmt.where(VirtualCard.is_active.is_(True))
    stmt = stmt.order_by(VirtualCard.created_at.desc())
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.post("/cards", response_model=VirtualCardOut, status_code=status.HTTP_201_CREATED)
async def create_card(
    payload: VirtualCardCreate,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualCard:
    """Issue a new virtual card linked to a parent account, establishing spending limits."""
    await _require_finance(db, current_user, "finance.cards.create")
    account = await db.get(VirtualAccount, payload.account_id)
    if not account or not account.is_active:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found or inactive.")

    last_four = "".join(random.choices(string.digits, k=4))
    card = VirtualCard(
        account_id=payload.account_id,
        holder_id=payload.holder_id,
        card_name=payload.card_name,
        last_four=last_four,
        card_type=payload.card_type,
        expires_month=payload.expires_month,
        expires_year=payload.expires_year,
        daily_limit_paise=payload.daily_limit_paise,
        monthly_limit_paise=payload.monthly_limit_paise,
    )
    db.add(card)
    await db.commit()
    await db.refresh(card)
    return card


@router.get("/cards/{card_id}", response_model=VirtualCardOut)
async def get_card(
    card_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualCard:
    """Get profile information for a specific virtual card by UUID."""
    await _require_finance(db, current_user, "finance.cards.read")
    card = await db.get(VirtualCard, card_id)
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found.")
    return card


@router.patch("/cards/{card_id}", response_model=VirtualCardOut)
async def update_card(
    card_id: uuid.UUID,
    payload: VirtualCardUpdate,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualCard:
    """Modify details, active status, or spending limit thresholds for a virtual card."""
    await _require_finance(db, current_user, "finance.cards.manage")
    card = await db.get(VirtualCard, card_id)
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found.")
    for field, value in payload.model_dump(exclude_unset=True).items():
        setattr(card, field, value)
    await db.commit()
    await db.refresh(card)
    return card


@router.delete("/cards/{card_id}", status_code=status.HTTP_204_NO_CONTENT)
async def deactivate_card(
    card_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> None:
    """Soft delete/deactivate a virtual card."""
    await _require_finance(db, current_user, "finance.cards.manage")
    card = await db.get(VirtualCard, card_id)
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found.")
    card.is_active = False
    await db.commit()


# ---------------------------------------------------------------------------
# Money Requests
# ---------------------------------------------------------------------------

@router.get("/requests", response_model=list[MoneyRequestOut])
async def list_requests(
    db: DbSession,
    current_user: CurrentUserDep,
    status_filter: Annotated[str | None, Query(alias="status")] = None,
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[MoneyRequest]:
    """List money requests, with optional filters for pending/approved status."""
    await _require_finance(db, current_user, "finance.requests.read")
    stmt = select(MoneyRequest).order_by(MoneyRequest.created_at.desc()).limit(limit).offset(offset)
    if status_filter:
        stmt = stmt.where(MoneyRequest.status == status_filter)
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.post("/requests", response_model=MoneyRequestOut, status_code=status.HTTP_201_CREATED)
async def create_request(
    payload: MoneyRequestCreate,
    db: DbSession,
    current_user: CurrentUserDep,
) -> MoneyRequest:
    """Submit a money draw request to pull balance into a virtual account."""
    await _require_finance(db, current_user, "finance.requests.create")

    # Validate destination account
    to_account = await db.get(VirtualAccount, payload.to_account_id)
    if not to_account or not to_account.is_active:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Destination account not found or inactive.")

    # If from_account specified, validate it
    if payload.from_account_id:
        from_account = await db.get(VirtualAccount, payload.from_account_id)
        if not from_account or not from_account.is_active:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Source account not found or inactive.")
        if payload.from_account_id == payload.to_account_id:
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Source and destination accounts must be different.")

    req = MoneyRequest(
        from_account_id=payload.from_account_id,
        to_account_id=payload.to_account_id,
        requester_id=current_user.user_id,
        amount_paise=payload.amount_paise,
        description=payload.description,
    )
    db.add(req)
    await db.commit()
    await db.refresh(req)
    return req


@router.get("/requests/{request_id}", response_model=MoneyRequestOut)
async def get_request(
    request_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
) -> MoneyRequest:
    """Retrieve details for a specific money request by UUID."""
    await _require_finance(db, current_user, "finance.requests.read")
    req = await db.get(MoneyRequest, request_id)
    if not req:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Request not found.")
    return req


@router.post("/requests/{request_id}/approve", response_model=MoneyRequestOut)
async def approve_request(
    request_id: uuid.UUID,
    payload: MoneyRequestReview,
    db: DbSession,
    current_user: CurrentUserDep,
) -> MoneyRequest:
    """Approve a pending money request, updating balances and appending a ledger transaction log entry."""
    await _require_finance(db, current_user, "finance.requests.approve")
    req_result = await db.execute(
        select(MoneyRequest).where(MoneyRequest.id == request_id).with_for_update()
    )
    req = req_result.scalar_one_or_none()
    if not req:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Request not found.")
    if req.status != "pending":
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Request is already {req.status}.")

    to_account_result = await db.execute(
        select(VirtualAccount)
        .where(VirtualAccount.id == req.to_account_id)
        .with_for_update()
    )
    to_account = to_account_result.scalar_one_or_none()
    if not to_account or not to_account.is_active:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Destination account is missing or inactive.",
        )

    from_account = None
    if req.from_account_id:
        from_account_result = await db.execute(
            select(VirtualAccount)
            .where(VirtualAccount.id == req.from_account_id)
            .with_for_update()
        )
        from_account = from_account_result.scalar_one_or_none()
        if not from_account or not from_account.is_active:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Source account is missing or inactive.",
            )
        if from_account.balance_paise < req.amount_paise:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Source account has insufficient balance.",
            )

    # Update balances (paper only)
    to_account.balance_paise += req.amount_paise
    if from_account:
        from_account.balance_paise -= req.amount_paise

    # Create ledger transaction
    transaction = VirtualTransaction(
        source_account_id=req.from_account_id,
        destination_account_id=req.to_account_id,
        amount_paise=req.amount_paise,
        reference_type="money_request",
        reference_id=req.id,
        description=f"Approved money request: {req.description}",
    )
    db.add(transaction)

    req.status = "approved"
    req.reviewed_by = current_user.user_id
    req.reviewed_at = datetime.now(timezone.utc)
    req.review_note = payload.note

    await db.commit()
    await db.refresh(req)
    return req


@router.post("/requests/{request_id}/reject", response_model=MoneyRequestOut)
async def reject_request(
    request_id: uuid.UUID,
    payload: MoneyRequestReview,
    db: DbSession,
    current_user: CurrentUserDep,
) -> MoneyRequest:
    """Reject a pending money request."""
    await _require_finance(db, current_user, "finance.requests.approve")
    req = await db.get(MoneyRequest, request_id)
    if not req:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Request not found.")
    if req.status != "pending":
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Request is already {req.status}.")

    req.status = "rejected"
    req.reviewed_by = current_user.user_id
    req.reviewed_at = datetime.now(timezone.utc)
    req.review_note = payload.note

    await db.commit()
    await db.refresh(req)
    return req


# ---------------------------------------------------------------------------
# Virtual Ledger Transactions & Simulation
# ---------------------------------------------------------------------------

@router.get("/transactions", response_model=list[VirtualTransactionOut])
async def list_all_transactions(
    db: DbSession,
    current_user: CurrentUserDep,
    limit: Annotated[int, Query(ge=1, le=100)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[VirtualTransaction]:
    """List recent transactions foundation-wide (for admins) or for owned accounts (for users)."""
    # Check if user has admin permission
    is_admin = await can(db, current_user, "finance.admin")
    
    if is_admin:
        stmt = select(VirtualTransaction).order_by(VirtualTransaction.created_at.desc()).limit(limit).offset(offset)
    else:
        # Users can only see transactions involving accounts they own
        user_accounts_stmt = select(VirtualAccount.id).where(VirtualAccount.owner_id == current_user.user_id)
        user_accounts_result = await db.execute(user_accounts_stmt)
        user_account_ids = user_accounts_result.scalars().all()
        
        if not user_account_ids:
            return []
            
        stmt = (
            select(VirtualTransaction)
            .where(
                VirtualTransaction.source_account_id.in_(user_account_ids) |
                VirtualTransaction.destination_account_id.in_(user_account_ids)
            )
            .order_by(VirtualTransaction.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.get("/accounts/{account_id}/transactions", response_model=list[VirtualTransactionOut])
async def list_account_transactions(
    account_id: uuid.UUID,
    db: DbSession,
    current_user: CurrentUserDep,
    limit: Annotated[int, Query(ge=1, le=100)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[VirtualTransaction]:
    """List ledger transactions where target account is source or destination."""
    await _require_finance(db, current_user, "finance.accounts.read")
    account = await db.get(VirtualAccount, account_id)
    if not account:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Account not found.")
    
    stmt = (
        select(VirtualTransaction)
        .where(
            (VirtualTransaction.source_account_id == account_id) |
            (VirtualTransaction.destination_account_id == account_id)
        )
        .order_by(VirtualTransaction.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.post("/cards/{card_id}/simulate-charge", response_model=VirtualTransactionOut)
async def simulate_card_charge(
    card_id: uuid.UUID,
    payload: CardSimulationPayload,
    db: DbSession,
    current_user: CurrentUserDep,
) -> VirtualTransaction:
    """Simulate a credit/debit card transaction, verifying balance and spending limits."""
    # 1. Fetch VirtualCard and verify
    card_result = await db.execute(
        select(VirtualCard).where(VirtualCard.id == card_id).with_for_update()
    )
    card = card_result.scalar_one_or_none()
    if not card:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Card not found.")
        
    # Check if active
    if not card.is_active:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Card is inactive.")
        
    # Check permission: holder of the card or finance admin
    if card.holder_id != current_user.user_id:
        await _require_finance(db, current_user, "finance.cards.manage")
        
    # 2. Fetch parent account
    account_result = await db.execute(
        select(VirtualAccount)
        .where(VirtualAccount.id == card.account_id)
        .with_for_update()
    )
    account = account_result.scalar_one_or_none()
    if not account or not account.is_active:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Parent virtual account not found or inactive.")
        
    # 3. Check account balance
    if account.balance_paise < payload.amount_paise:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Decline: Insufficient balance. Card requires {payload.amount_paise} paise, account balance is {account.balance_paise} paise."
        )
        
    # 4. Check card limits (daily and monthly)
    # Daily Limit Check (last 24 hours)
    if card.daily_limit_paise is not None:
        cutoff_24h = datetime.now(timezone.utc) - timedelta(days=1)
        daily_sum_stmt = (
            select(func.sum(VirtualTransaction.amount_paise))
            .where(
                VirtualTransaction.reference_type == "card_charge",
                VirtualTransaction.reference_id == card.id,
                VirtualTransaction.created_at >= cutoff_24h
            )
        )
        daily_sum_res = await db.execute(daily_sum_stmt)
        daily_spent = daily_sum_res.scalar() or 0
        if daily_spent + payload.amount_paise > card.daily_limit_paise:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Decline: Transaction exceeds daily limit. Spent: {daily_spent} paise, Limit: {card.daily_limit_paise} paise."
            )
            
    # Monthly Limit Check (current calendar month)
    if card.monthly_limit_paise is not None:
        now = datetime.now(timezone.utc)
        start_of_month = datetime(now.year, now.month, 1, tzinfo=timezone.utc)
        monthly_sum_stmt = (
            select(func.sum(VirtualTransaction.amount_paise))
            .where(
                VirtualTransaction.reference_type == "card_charge",
                VirtualTransaction.reference_id == card.id,
                VirtualTransaction.created_at >= start_of_month
            )
        )
        monthly_sum_res = await db.execute(monthly_sum_stmt)
        monthly_spent = monthly_sum_res.scalar() or 0
        if monthly_spent + payload.amount_paise > card.monthly_limit_paise:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Decline: Transaction exceeds monthly limit. Spent: {monthly_spent} paise, Limit: {card.monthly_limit_paise} paise."
            )
            
    # 5. Atomic Update: decrement parent account balance
    account.balance_paise -= payload.amount_paise
    
    # Create the VirtualTransaction
    transaction = VirtualTransaction(
        source_account_id=card.account_id,
        destination_account_id=None,
        amount_paise=payload.amount_paise,
        reference_type="card_charge",
        reference_id=card.id,
        description=f"Card charge: {payload.merchant} - {payload.description}",
    )
    db.add(transaction)
    
    await db.commit()
    await db.refresh(transaction)
    return transaction
