"use client";

import { FormEvent, useEffect, useState } from "react";

type BlockType = "heading" | "paragraph" | "text" | "textarea" | "email" | "choice" | "multichoice" | "select" | "file" | "divider" | "consent";
type Block = { id: string; type: BlockType; label: string; description?: string; required?: boolean; options?: string[] };
type FormData = { title: string; slug: string; description_markdown?: string; blocks: Block[] };
const allowed = ["application/pdf", "image/jpeg", "image/png", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];

export function PublicFormClient({ slug }: { slug: string }) {
  const [form, setForm] = useState<FormData | null>(null), [answers, setAnswers] = useState<Record<string, string | string[]>>({}), [files, setFiles] = useState<Record<string, File[]>>({}), [terms, setTerms] = useState(false), [status, setStatus] = useState("");
  useEffect(() => { fetch(`/api/forms/public/${slug}`).then(async (response) => response.ok ? setForm(await response.json()) : setStatus("This form is no longer available.")); }, [slug]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!form || !terms) return setStatus("Please accept the terms before submitting."); const missing = form.blocks.find((block) => block.required && block.type !== "consent" && !(block.type === "file" ? files[block.id]?.length : hasAnswer(answers[block.id]))); if (missing) return setStatus(`Please complete: ${missing.label}`); const selected = Object.values(files).flat(); if (selected.length > 5) return setStatus("You can upload at most five files."); if (selected.some((file) => file.size > 2 * 1024 * 1024 || !allowed.includes(file.type))) return setStatus("Upload PDF, JPG, PNG, or DOCX files under 2 MB."); setStatus("Submitting…"); const idempotencyKey = crypto.randomUUID(); const response = await fetch(`/api/forms/public/${slug}/submissions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers, accepted_terms: terms, idempotency_key: idempotencyKey }) }); const payload = await response.json(); if (!response.ok) return setStatus(payload.detail || "Could not submit your response."); for (const [fieldId, selectedFiles] of Object.entries(files)) for (const file of selectedFiles) { const data = new FormData(); data.append("field_id", fieldId); data.append("file", file); if (!(await fetch(`/api/forms/public/submissions/${payload.id}/uploads`, { method: "POST", body: data })).ok) return setStatus("Your response was received, but a file could not be uploaded. Please contact us."); } setStatus("Thanks — your response has been received."); }
  if (!form) return <main className="grid min-h-dvh place-items-center bg-[#faf8f5] p-6 text-[#120f0a]"><p className="font-mono text-sm">{status || "Loading form…"}</p></main>;
  const hasConsent = form.blocks.some((block) => block.type === "consent");
  return <main className="min-h-dvh bg-[#faf8f5] px-4 py-8 text-[#120f0a] sm:px-6 sm:py-14"><div className="mx-auto max-w-2xl"><header className="border-2 border-[#120f0a] bg-white p-6 shadow-[5px_5px_0_#120f0a] sm:p-9"><a className="grid h-16 w-16 place-items-center bg-[#120f0a] p-2" href="https://gobitsnbytes.org" aria-label="bits&bytes™ home"><img src="https://gobitsnbytes.org/logo" alt="bits&bytes™ logo" className="h-12 w-auto"/></a><p className="mt-5 font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-[#97192c]">bits&amp;bytes™</p><h1 className="mt-3 font-heading text-3xl font-black leading-tight sm:text-5xl">{form.title}</h1>{form.description_markdown && <p className="mt-4 whitespace-pre-wrap font-base text-base leading-7">{form.description_markdown}</p>}</header><form onSubmit={submit} className="mt-8 space-y-6">{form.blocks.map((block) => <PublicBlock key={block.id} block={block} answers={answers} files={files} terms={terms} setAnswers={setAnswers} setFiles={setFiles} setTerms={setTerms}/>)}{!hasConsent && <label className="flex min-h-11 items-start gap-3 border-2 border-[#120f0a] bg-white p-4 text-sm leading-6"><input required checked={terms} onChange={(event) => setTerms(event.target.checked)} type="checkbox" className="mt-1"/>I agree to the applicable bits&amp;bytes™ terms and privacy practices for this form.</label>}<button className="min-h-12 w-full border-2 border-[#120f0a] bg-[#97192c] px-5 font-heading font-black text-white shadow-[5px_5px_0_#120f0a] active:translate-x-1 active:translate-y-1 active:shadow-none">Submit response</button>{status && <p role="status" className="font-medium">{status}</p>}</form><footer className="mt-10 border-t-2 border-[#120f0a] pt-5 text-center font-mono text-[10px] leading-5 text-[#413f3b]"><p>bits&amp;bytes™ by GOBITSNBYTES FOUNDATION</p><p>© 2026 GOBITSNBYTES FOUNDATION. All rights reserved. | <a className="underline underline-offset-2 hover:text-[#97192c]" href="https://gobitsnbytes.org">gobitsnbytes.org</a></p></footer></div></main>;
}

const hasAnswer = (answer: string | string[] | undefined) => Array.isArray(answer) ? answer.length > 0 : !!answer;

function PublicBlock({ block, answers, files, terms, setAnswers, setFiles, setTerms }: { block: Block; answers: Record<string, string | string[]>; files: Record<string, File[]>; terms: boolean; setAnswers: (answers: Record<string, string | string[]>) => void; setFiles: (files: Record<string, File[]>) => void; setTerms: (terms: boolean) => void }) {
  if (block.type === "heading") return <h2 className="pt-5 font-heading text-2xl font-black">{block.label}</h2>;
  if (block.type === "paragraph") return <p className="whitespace-pre-wrap leading-7">{block.label}</p>;
  if (block.type === "divider") return <hr className="border-t-2 border-[#120f0a]"/>;
  if (block.type === "consent") return <label className="flex min-h-11 items-start gap-3 border-2 border-[#120f0a] bg-white p-4 text-sm leading-6"><input required checked={terms} onChange={(event) => setTerms(event.target.checked)} type="checkbox" className="mt-1"/>{block.label}</label>;
  const set = (value: string) => setAnswers({ ...answers, [block.id]: value });
  const toggle = (value: string) => { const answer = answers[block.id]; const values = Array.isArray(answer) ? answer : []; setAnswers({ ...answers, [block.id]: values.includes(value) ? values.filter((item) => item !== value) : [...values, value] }); };
  const answer = answers[block.id];
  return <fieldset className="border-2 border-[#120f0a] bg-white p-5 shadow-[4px_4px_0_#120f0a]"><label className="block font-heading text-lg font-bold">{block.label}{block.required && <span className="ml-1 text-[#97192c]">*</span>}</label>{block.description && <p className="mt-1 text-sm text-stone-600">{block.description}</p>}{block.type === "textarea" ? <textarea required={block.required} value={typeof answer === "string" ? answer : ""} onChange={(event) => set(event.target.value)} className="mt-4 min-h-32 w-full border-2 border-[#120f0a] p-3 text-base outline-none focus:border-[#97192c]"/> : block.type === "choice" ? <div className="mt-4 space-y-3">{(block.options || []).map((option) => <label key={option} className="flex min-h-11 items-center gap-3"><input required={block.required} type="radio" name={block.id} onChange={() => set(option)}/>{option}</label>)}</div> : block.type === "multichoice" ? <div className="mt-4 space-y-3">{(block.options || []).map((option) => <label key={option} className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={Array.isArray(answer) && answer.includes(option)} onChange={() => toggle(option)}/>{option}</label>)}</div> : block.type === "select" ? <select required={block.required} value={typeof answer === "string" ? answer : ""} onChange={(event) => set(event.target.value)} className="mt-4 min-h-11 w-full border-2 border-[#120f0a] bg-white p-3 text-base outline-none focus:border-[#97192c]"><option value="">Select an option</option>{(block.options || []).map((option) => <option key={option}>{option}</option>)}</select> : <input required={block.required} multiple={block.type === "file"} type={block.type === "email" ? "email" : block.type === "file" ? "file" : "text"} onChange={(event) => block.type === "file" ? setFiles({ ...files, [block.id]: Array.from(event.currentTarget.files || []) }) : set(event.currentTarget.value)} className="mt-4 min-h-11 w-full border-2 border-[#120f0a] p-3 text-base outline-none focus:border-[#97192c]"/>}{block.type === "file" && <p className="mt-2 text-sm">Up to 5 files total, 2 MB each. Files are deleted after 30 days.</p>}</fieldset>;
}
