"""add_discord_bot_tables

Revision ID: 13ecd7a65443
Revises: cdd5a04f9914
Create Date: 2026-06-26 00:29:46.603946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13ecd7a65443'
down_revision: Union[str, Sequence[str], None] = 'cdd5a04f9914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_job_runs',
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('period_key', sa.String(length=255), nullable=False),
    sa.Column('ran_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('job_name', 'period_key')
    )
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('val', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('fork_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_attendees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actual_attendees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_email_preferences',
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('notify_on_invite', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notify_on_reminder', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.BigInteger(), nullable=False),
    sa.Column('location_type', sa.String(length=100), nullable=False),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.Column('temp_channel_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('calcom_booking_id', sa.String(length=255), nullable=True),
    sa.Column('calcom_uid', sa.String(length=255), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('external_emails', sa.Text(), nullable=True),
    sa.Column('recording_status', sa.String(length=50), server_default='none', nullable=False),
    sa.Column('meet_code', sa.String(length=100), nullable=True),
    sa.Column('booked_by', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=50), server_default='invite', nullable=False),
    sa.Column('activated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meet_code')
    )
    op.create_table('pending_notion_profiles',
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.BigInteger(), nullable=False),
    sa.Column('last_reminded_at', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('discord_id', 'city')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('fork_id', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('submitted_date', sa.String(length=100), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('fork_id', sa.String(length=100), nullable=False),
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('joined_date', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_availability',
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default='Asia/Kolkata', nullable=False),
    sa.Column('weekly_hours', sa.Text(), nullable=True),
    sa.Column('booking_link', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calcom_event_type_id', sa.String(length=100), nullable=True),
    sa.Column('associated_role_id', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('discord_id'),
    sa.UniqueConstraint('booking_link')
    )
    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=False),
    sa.Column('discord_id', sa.String(length=100), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('notified_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_items_discord_status', 'action_items', ['discord_id', 'status'], unique=False)
    op.create_table('meeting_attendance_pings',
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('last_ping_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    op.create_table('meeting_attendees',
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('attendee_type', sa.String(length=100), nullable=False),
    sa.Column('discord_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'attendee_type', 'discord_id')
    )
    op.create_table('meeting_reminders_sent',
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('reminder_type', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'reminder_type')
    )
    op.create_table('meeting_reschedule_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('old_scheduled_time', sa.BigInteger(), nullable=False),
    sa.Column('old_end_time', sa.BigInteger(), nullable=True),
    sa.Column('new_scheduled_time', sa.BigInteger(), nullable=False),
    sa.Column('new_end_time', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rescheduled_by', sa.String(length=100), nullable=False),
    sa.Column('rescheduled_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_transcripts',
    sa.Column('meeting_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_decisions', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('full_transcript', sa.Text(), nullable=True),
    sa.Column('timestamped_transcript', sa.Text(), nullable=True),
    sa.Column('vc_text_messages', sa.Text(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_transcripts')
    op.drop_table('meeting_reschedule_history')
    op.drop_table('meeting_reminders_sent')
    op.drop_table('meeting_attendees')
    op.drop_table('meeting_attendance_pings')
    op.drop_index('idx_action_items_discord_status', table_name='action_items')
    op.drop_table('action_items')
    op.drop_table('web_sessions')
    op.drop_table('user_availability')
    op.drop_table('team_members')
    op.drop_table('reports')
    op.drop_table('push_subscriptions')
    op.drop_table('pending_notion_profiles')
    op.drop_table('meetings')
    op.drop_table('meeting_email_preferences')
    op.drop_table('events')
    op.drop_table('bot_settings')
    op.drop_table('bot_job_runs')
    # ### end Alembic commands ###
