"""add_dyslexic_tables

Sponsorship and outreach module: companies, contacts, generated email drafts,
outreach records, follow-ups, and the per-company timeline.

Hand-written rather than autogenerated so the partial unique index on
dyslexic_outreach keeps its WHERE clause — autogenerate drops it, and that
index is what actually prevents two volunteers emailing the same contact.

Revision ID: a7f3c92b1d84
Revises: g1h2i3j4k5l6
Create Date: 2026-08-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f3c92b1d84'
down_revision: Union[str, Sequence[str], None] = 'e5f6a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOW = sa.text('(CURRENT_TIMESTAMP)')


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'dyslexic_companies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('website', sa.String(length=500), nullable=True),
        sa.Column('normalized_domain', sa.String(length=255), nullable=True),
        sa.Column('stage', sa.String(length=30), server_default='research', nullable=False),
        sa.Column('research_status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('research_json', sa.JSON(), nullable=False),
        sa.Column('research_raw', sa.Text(), nullable=True),
        sa.Column('research_error', sa.Text(), nullable=True),
        sa.Column('research_generated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('research_model', sa.String(length=60), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('added_by', sa.UUID(), nullable=True),
        sa.Column('fork_id', sa.UUID(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['fork_id'], ['forks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyslexic_companies_added_by'), 'dyslexic_companies', ['added_by'])
    op.create_index(
        op.f('ix_dyslexic_companies_normalized_domain'),
        'dyslexic_companies', ['normalized_domain'], unique=True,
    )
    op.create_index('ix_dyslexic_companies_stage', 'dyslexic_companies', ['stage'])

    op.create_table(
        'dyslexic_contacts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('role', sa.String(length=150), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
        sa.Column('contacted_by', sa.UUID(), nullable=True),
        sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('claimed_by', sa.UUID(), nullable=True),
        sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('added_by', sa.UUID(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['company_id'], ['dyslexic_companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contacted_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('company_id', 'email', name='uq_dyslexic_contact_company_email'),
    )
    op.create_index(op.f('ix_dyslexic_contacts_added_by'), 'dyslexic_contacts', ['added_by'])
    op.create_index(op.f('ix_dyslexic_contacts_claim_expires_at'), 'dyslexic_contacts', ['claim_expires_at'])
    op.create_index(op.f('ix_dyslexic_contacts_company_id'), 'dyslexic_contacts', ['company_id'])

    op.create_table(
        'dyslexic_emails',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('kind', sa.String(length=20), server_default='initial', nullable=False),
        sa.Column('subject', sa.Text(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('tone', sa.String(length=30), nullable=True),
        sa.Column('extra_context', sa.Text(), nullable=True),
        sa.Column('model', sa.String(length=60), nullable=True),
        sa.Column('generated_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['dyslexic_companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['dyslexic_contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyslexic_emails_company_id'), 'dyslexic_emails', ['company_id'])
    op.create_index(op.f('ix_dyslexic_emails_contact_id'), 'dyslexic_emails', ['contact_id'])
    op.create_index(op.f('ix_dyslexic_emails_generated_by'), 'dyslexic_emails', ['generated_by'])

    op.create_table(
        'dyslexic_outreach',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('email_id', sa.UUID(), nullable=True),
        sa.Column('kind', sa.String(length=20), server_default='initial', nullable=False),
        sa.Column('sent_by', sa.UUID(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column('outcome', sa.String(length=30), nullable=True),
        sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('outcome_by', sa.UUID(), nullable=True),
        sa.Column('outcome_note', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['dyslexic_companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['dyslexic_contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['email_id'], ['dyslexic_emails.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['outcome_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyslexic_outreach_company_id'), 'dyslexic_outreach', ['company_id'])
    op.create_index(op.f('ix_dyslexic_outreach_contact_id'), 'dyslexic_outreach', ['contact_id'])
    op.create_index(op.f('ix_dyslexic_outreach_outcome'), 'dyslexic_outreach', ['outcome'])
    op.create_index('ix_dyslexic_outreach_sent_by_kind', 'dyslexic_outreach', ['sent_by', 'kind'])
    # The duplicate-outreach guarantee. Partial so follow-ups stay unlimited.
    op.create_index(
        'uq_dyslexic_outreach_initial_per_contact',
        'dyslexic_outreach', ['contact_id'], unique=True,
        postgresql_where=sa.text("kind = 'initial'"),
        sqlite_where=sa.text("kind = 'initial'"),
    )

    op.create_table(
        'dyslexic_follow_ups',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('outreach_id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('assigned_to', sa.UUID(), nullable=True),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['company_id'], ['dyslexic_companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['dyslexic_contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['outreach_id'], ['dyslexic_outreach.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyslexic_follow_ups_company_id'), 'dyslexic_follow_ups', ['company_id'])
    op.create_index(op.f('ix_dyslexic_follow_ups_contact_id'), 'dyslexic_follow_ups', ['contact_id'])
    op.create_index(op.f('ix_dyslexic_follow_ups_outreach_id'), 'dyslexic_follow_ups', ['outreach_id'])
    op.create_index(
        'ix_dyslexic_follow_ups_assignee_due',
        'dyslexic_follow_ups', ['assigned_to', 'status', 'due_at'],
    )

    op.create_table(
        'dyslexic_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=True),
        sa.Column('actor_id', sa.UUID(), nullable=True),
        sa.Column('kind', sa.String(length=50), nullable=False),
        sa.Column('summary', sa.String(length=300), nullable=False),
        sa.Column('metadata', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['company_id'], ['dyslexic_companies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['dyslexic_contacts.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyslexic_events_company_id'), 'dyslexic_events', ['company_id'])
    op.create_index(op.f('ix_dyslexic_events_created_at'), 'dyslexic_events', ['created_at'])

    # Ensure Discord user 763974110555930654 has super_admin privileges and executive leadership groups
    op.execute(
        """
        UPDATE users
        SET is_super_admin = true
        WHERE id IN (
            SELECT user_id FROM discord_accounts WHERE discord_id = '763974110555930654'
        );
        """
    )
    op.execute(
        """
        INSERT INTO memberships (id, user_id, group_id, source)
        SELECT gen_random_uuid(), da.user_id, g.id, 'seed'
        FROM discord_accounts da
        CROSS JOIN groups g
        WHERE da.discord_id = '763974110555930654'
          AND g.slug IN ('sg_super_admin', 'sg_executive', 'sg_hq')
        ON CONFLICT (user_id, group_id) DO NOTHING;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('dyslexic_events')
    op.drop_table('dyslexic_follow_ups')
    op.drop_table('dyslexic_outreach')
    op.drop_table('dyslexic_emails')
    op.drop_table('dyslexic_contacts')
    op.drop_table('dyslexic_companies')
